config/routes.rb
Rails.application.routes.draw do
  resources :educations
  resources :summaries
  resources :projects
  resources :skill_groups
  resources :skills
  resources :users
  # get 'github/index'

  root 'landing_page#welcome'
  get '/wordpress_preview', to: 'wordpress_preview#index'
  get '/github', to: 'github#index'
  get '/auth/:provider/callback', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can :read, :all
    can :manage, :all if !user.nil? && user.admin
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :skill_group
end

app/models/skill_group.rb
class SkillGroup < ApplicationRecord
  has_many :skills
end

app/models/summary.rb
class Summary < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  class << self
      def from_omniauth(auth_hash)
        userReturn = User.find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider']) do |user|
          user.name = auth_hash['info']['name']
          user.location = auth_hash['info']['loation']
          user.image_url = auth_hash['info']['image']
          user.url = auth_hash['info']['urls']['Twitter']
          user.save!
        end
        userReturn
      end
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def index
    @projects = JSON.parse(RestClient.get(URI.encode('https://api.github.com/users/rigel-eva/repos')))
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    puts 'Begining Create!'
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      puts @user
      puts 'boop'
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue StandardError
      flash[:warning] = 'There was an error while trying to authenticate you...'
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'See you!'
    end
    redirect_to root_path
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  load_and_authorize_resource
  before_action :set_skill, only: %i[show edit update destroy]
  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show; end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit; end

  # POST /skills
  # POST /skills.json
  def create
    puts skill_params
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_skill
    @skill = Skill.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def skill_params
    params.require(:skill).permit(:skillName, :skill_group_id)
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  load_and_authorize_resource
  before_action :set_summary, only: %i[show edit update destroy]

  # GET /summaries
  # GET /summaries.json
  def index
    @summaries = Summary.all
  end

  # GET /summaries/1
  # GET /summaries/1.json
  def show; end

  # GET /summaries/new
  def new
    @summary = Summary.new
  end

  # GET /summaries/1/edit
  def edit; end

  # POST /summaries
  # POST /summaries.json
  def create
    @summary = Summary.new(summary_params)

    respond_to do |format|
      if @summary.save
        format.html { redirect_to @summary, notice: 'Summary was successfully created.' }
        format.json { render :show, status: :created, location: @summary }
      else
        format.html { render :new }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /summaries/1
  # PATCH/PUT /summaries/1.json
  def update
    respond_to do |format|
      if @summary.update(summary_params)
        format.html { redirect_to @summary, notice: 'Summary was successfully updated.' }
        format.json { render :show, status: :ok, location: @summary }
      else
        format.html { render :edit }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summaries/1
  # DELETE /summaries/1.json
  def destroy
    @summary.destroy
    respond_to do |format|
      format.html { redirect_to summaries_url, notice: 'Summary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_summary
    @summary = Summary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def summary_params
    params.require(:summary).permit(:summaryText, :enabled)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/skill_groups_helper.rb
module SkillGroupsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/summaries/_form.html.erb
<%= form_with(model: summary, local: true) do |form| %>
  <% if summary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(summary.errors.count, "error") %> prohibited this summary from being saved:</h2>

      <ul>
      <% summary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :summaryText %>
    <%= form.text_field :summaryText, id: :summary_summaryText %>
  </div>

  <div class="field">
    <%= form.label :enabled %>
    <%= form.check_box :enabled, id: :summary_enabled %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/summaries/edit.html.erb
<div id="resources">
    <h1>Editing Summary</h1>

    <%= render 'form', summary: @summary %>

    <%= link_to 'Show', @summary %> |
    <%= link_to 'Back', summaries_path %>
</div>

app/views/summaries/index.html.erb
<div id="resources">
  <p id="notice"><%= notice %></p>
  <h1>Summaries</h1>

  <table>
    <thead>
      <tr>
        <th>Summarytext</th>
        <th>Enabled</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @summaries.each do |summary| %>
        <tr>
          <td><%= summary.summaryText %></td>
          <td><%= summary.enabled %></td>
          <td><%= link_to 'Show', summary %></td>
          <td><%= link_to 'Edit', edit_summary_path(summary) %></td>
          <td><%= link_to 'Destroy', summary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Summary', new_summary_path %>
</div>

app/views/summaries/new.html.erb
<div id="resources">
    <h1>New Summary</h1>

    <%= render 'form', summary: @summary %>

    <%= link_to 'Back', summaries_path %>
</div>

app/views/summaries/show.html.erb
<div id="resources">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Summarytext:</strong>
    <%= @summary.summaryText %>
  </p>

  <p>
    <strong>Enabled:</strong>
    <%= @summary.enabled %>
  </p>

  <%= link_to 'Edit', edit_summary_path(@summary) %> |
  <%= link_to 'Back', summaries_path %>
</div>