config/routes.rb
Rails.application.routes.draw do
  resources :educations
  resources :summaries
  resources :projects
  resources :skill_groups
  resources :skills
  resources :users
  # get 'github/index'

  root 'landing_page#welcome'
  get '/wordpress_preview', to: 'wordpress_preview#index'
  get '/github', to: 'github#index'
  get '/auth/:provider/callback', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can :read, :all
    can :manage, :all if !user.nil? && user.admin
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :skill_group
end

app/models/skill_group.rb
class SkillGroup < ApplicationRecord
  has_many :skills
end

app/models/summary.rb
class Summary < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  class << self
      def from_omniauth(auth_hash)
        userReturn = User.find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider']) do |user|
          user.name = auth_hash['info']['name']
          user.location = auth_hash['info']['loation']
          user.image_url = auth_hash['info']['image']
          user.url = auth_hash['info']['urls']['Twitter']
          user.save!
        end
        userReturn
      end
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def index
    @projects = JSON.parse(RestClient.get(URI.encode('https://api.github.com/users/rigel-eva/repos')))
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:projectName, :projectStartDate, :projectEndDate, :projectInfo, :current, :client)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    puts 'Begining Create!'
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      puts @user
      puts 'boop'
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue StandardError
      flash[:warning] = 'There was an error while trying to authenticate you...'
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'See you!'
    end
    redirect_to root_path
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  load_and_authorize_resource
  before_action :set_skill, only: %i[show edit update destroy]
  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show; end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit; end

  # POST /skills
  # POST /skills.json
  def create
    puts skill_params
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_skill
    @skill = Skill.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def skill_params
    params.require(:skill).permit(:skillName, :skill_group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/skill_groups_helper.rb
module SkillGroupsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, onload:"nilAndDisableDate()") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :projectName %>
    <%= form.text_field :projectName, id: :project_projectName %>
  </div>
  <div class="field">
   <%= form.label :client%>
   <%= form.text_field :client, id: :project_client%>
  </div>
  <div class="field">
    <%= form.label :projectStartDate %>
    <%= form.date_select :projectStartDate, id: :project_projectStartDate %>
  </div>

  <div class="field">
    <%= form.label :projectEndDate %>
    <%= form.date_select :projectEndDate, id: :project_projectEndDate %>
    <%= form.label "Current"%>
    <%= form.check_box :current, id: :project_current%>
  </div>

  <div class="field">
    <%= form.label :projectInfo %>
    <%= form.text_area :projectInfo, id: :project_projectInfo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div id="resources">
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div id="resources">
  <p id="notice"><%= notice %></p>

  <h1>Projects</h1>

  <table>
    <thead>
      <tr>
        <th>Projectname</th>
        <th>Projectstartdate</th>
        <th>Projectenddate</th>
        <th>Projectinfo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.projectName %></td>
          <td><%= project.projectStartDate %></td>
          <td><%= project.projectEndDate %></td>
          <td><%= project.projectInfo %></td>
          <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<div id="resources">
    <h1>New Project</h1>

    <%= render 'form', project: @project %>

    <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div id="resources">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @project.projectName %>
  </p>
  <p>
    <strong> Client:</strong>
    <%= @project.client %>
  </p>
  <p>
    <strong>Start Date:</strong>
    <%= @project.projectStartDate %>
  </p>

  <p>
    <strong> End Date:</strong>
    <%= @project.projectEndDate %>
  </p>

  <p>
    <strong>Info:</strong>
    <%= simple_format(@project.projectInfo) %>
  </p>

  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %>
</div>

app/views/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :skillName %>
    <%= form.text_field :skillName, id: :skill_skillName %>
  </div>
  <div class="field">
    <%= form.label "Skill Catagory"%>
    <%= form.select :skill_group_id, SkillGroup.all.collect{|sg| [sg.skillType, sg.id]}, {include_blank: true}%>
  </div>>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<div id="resources">
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>
</div>

app/views/skills/index.html.erb
<div id="resources">
<p id="notice"><%= notice %></p>
<h1>Skills</h1>
  <div class="row">
    <div class="col-xs-2">Skill Name</div>
    <div class="col-xs-2">Skill Type</div>
  </div>
  <% @skills.each do |skill| %>
    <div class="row">
      <div class="col-xs-2"><%= skill.skillName %></div>
      <div class="col-xs-7"><%= skill.skill_group.skillType%></div>
      <div class="col-xs-1"><%= link_to 'Show', skill %></div>
      <div class="col-xs-1"><%= link_to 'Edit', edit_skill_path(skill) %></div>
      <div class="col-xs-1"><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    </div>
  <% end %>
  <br>

<%= link_to 'New Skill', new_skill_path %>
</div>

app/views/skills/new.html.erb
<div id="resources">
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>
</div>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>
<div id="resources">
<p>
  <strong>Skillname:</strong>
  <%= @skill.skillName %>
</p>

<p>
  <strong>Skilltype:</strong>
  <%= @skill.skill_group.skillType %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">
        <h1>Sign up</h1>
        <%= form_for @user do |f|%>
            <%= f.label :username%>
            <%= f.text_field :username%>
            <%=f.label :email%>
            <%=f.email_field :email%>
            <%=f.label :password%>
            <%=f.password_field :password%>
            <%=f.submit%>
        <%end%>
    </div>
  </div>
</div>